# Generated by Django 2.0.7 on 2021-04-02 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20210402_1454'),
        ('contest', '0002_auto_20210330_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.Campus'),
            preserve_default=False,
        ),
    ]
