# Generated by Django 2.0.7 on 2020-12-02 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201113_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(limit_choices_to={'short_name': 'super'}, on_delete=django.db.models.deletion.CASCADE, to='authentication.Role'),
        ),
    ]
