# Generated by Django 2.0.7 on 2021-04-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JudgeServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=300)),
                ('port', models.IntegerField()),
                ('status', models.CharField(blank=True, choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], max_length=200)),
                ('server_name', models.CharField(blank=True, max_length=600)),
                ('server_cpu_number', models.IntegerField(blank=True)),
                ('server_cpu_usage', models.IntegerField(blank=True)),
                ('server_memory_usage', models.IntegerField(blank=True)),
            ],
        ),
    ]
