# Generated by Django 2.0.7 on 2021-04-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgeserver',
            name='server_cpu_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='judgeserver',
            name='server_cpu_usage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='judgeserver',
            name='server_memory_usage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='judgeserver',
            name='status',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('abnormal', 'Abnormal')], max_length=200, null=True),
        ),
    ]
