# Generated by Django 2.0.7 on 2021-04-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeserver', '0003_auto_20210401_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgeserver',
            name='commnad_runner_version',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='judgeserver',
            name='load',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='judgeserver',
            name='address',
            field=models.CharField(max_length=1200, unique=True),
        ),
    ]
