# Generated by Django 2.0.7 on 2021-04-01 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgeserver', '0004_auto_20210401_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='judgeserver',
            old_name='commnad_runner_version',
            new_name='command_runner_version',
        ),
    ]
