# Generated by Django 2.0.7 on 2021-04-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeserver', '0005_auto_20210401_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgeserver',
            name='disabled',
        ),
        migrations.AddField(
            model_name='judgeserver',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
