# Generated by Django 2.0.7 on 2021-04-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judgeserver', '0007_judgeserver_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgeserver',
            name='port',
            field=models.PositiveIntegerField(default='5000'),
            preserve_default=False,
        ),
    ]
