# Generated by Django 2.0.7 on 2021-04-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgeserver', '0008_judgeserver_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgeserver',
            name='port',
        ),
    ]
