# Generated by Django 2.0.7 on 2020-11-20 11:05

import authentication.validators
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import problem.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter problem title', max_length=200, unique=True)),
                ('short_name', models.CharField(max_length=10)),
                ('pdf', models.FileField(unique=True, upload_to=problem.models.problem_directory_upload, validators=[authentication.validators.validate_problem_file_extension])),
                ('point', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('time_limit', models.DecimalField(decimal_places=2, help_text='enter time limit in second', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('memory_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Enter memory limit in mega bytes', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('ballon', models.CharField(default='#ffffff', max_length=10)),
                ('error', models.DecimalField(decimal_places=20, default=0.0, help_text='maximum absolute or relative error', max_digits=22, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('input', models.FileField(upload_to=problem.models.testcase_directory_upload, validators=[authentication.validators.validate_testcase_in_file_extension])),
                ('output', models.FileField(upload_to=problem.models.testcase_directory_upload, validators=[authentication.validators.validate_testcase_out_file_extension])),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('problem', 'input', 'output')},
        ),
    ]
