# Generated by Django 2.0.7 on 2021-04-26 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='max_output_size',
            field=models.PositiveIntegerField(default=1048576, help_text='max output size in byte', validators=[django.core.validators.MaxValueValidator(1048576)]),
        ),
    ]
