# Generated by Django 2.0.7 on 2021-04-30 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_problem_max_output_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('problem', 'name')},
        ),
    ]
