# Generated by Django 2.0.7 on 2020-11-13 21:44
from django.core.management import call_command
from django.db import migrations
def loadfixture(app, schema_editor):
    call_command('loaddata', 'com_initial_data.json')

class Migration(migrations.Migration):

    dependencies = [
        ('competitive', '0001_initial'),
    ]
    operations = [
        migrations.RunPython(loadfixture),
    ]
   