# Generated by Django 2.0.7 on 2021-04-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitive', '0002_auto_20201113_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecachejury',
            name='judging',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scorecachepublic',
            name='judging',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
