# Generated by Django 2.0.7 on 2021-04-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitive', '0003_auto_20210408_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='host',
            field=models.CharField(default='127.0.0.1:5000', max_length=200),
            preserve_default=False,
        ),
    ]
