# Generated by Django 2.0.7 on 2021-04-27 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('judgeserver', '0008_judgeserver_port'),
        ('competitive', '0004_submit_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit',
            name='host',
        ),
        migrations.AddField(
            model_name='submit',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='judgeserver.JudgeServer'),
            preserve_default=False,
        ),
    ]
