# Generated by Django 2.0.7 on 2021-04-27 15:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitive', '0006_auto_20210427_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseoutput',
            name='execution_time',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=22, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='testcaseoutput',
            name='memory_usage',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=22, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
