# Generated by Django 2.0.7 on 2021-04-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitive', '0008_auto_20210427_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseoutput',
            name='output_file',
            field=models.FilePathField(max_length=500),
        ),
    ]
