# Generated by Django 2.0.7 on 2021-04-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitive', '0010_auto_20210427_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseoutput',
            name='output_file',
            field=models.FilePathField(path='/home/images'),
        ),
    ]
