# Generated by Django 2.0.7 on 2021-04-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitive', '0014_auto_20210427_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseoutput',
            name='output_file',
            field=models.FilePathField(allow_folders=True, path='/home/andalus'),
        ),
    ]
