# Generated by Django 2.0.7 on 2021-04-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_problem_max_output_size'),
        ('competitive', '0015_auto_20210427_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcaseoutput',
            name='output_file',
            field=models.FilePathField(path='/home/andalus'),
        ),
        migrations.AlterUniqueTogether(
            name='testcaseoutput',
            unique_together={('test_case', 'submit')},
        ),
    ]
