# Generated by Django 2.0.7 on 2021-04-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitive', '0017_remove_testcaseoutput_output_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='submit',
            name='output_path',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
