# Generated by Django 2.0.7 on 2021-04-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20201113_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='help',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
